### ISSUE TITLE
Manage gem dependencies via Gemfile/Gemfile.lock

### ISSUE THREAD

**Issue by mdb** [CityOfPhiladelphia/analytics.phila.gov#13]
The README currently instructs developers to `gem install sass bourbon neat`.

However, this may result in the installation of gem versions incompatible with those installed by the original developer, and thus incompatible with the analytics.phila.gov codebase.

A `Gemfile` and `Gemfile.lock` can be used to lock the full dependency chain as intended.

**Comment by laurenancona** [comment]
Fixed by #14
