### ISSUE TITLE
Top 20 link errors

### ISSUE THREAD

**Issue by michaelck** [CityOfPhiladelphia/analytics.phila.gov#18]
Links listed under the Top 20, Now column are prepended with "undefined" resulting in DNS errors.

Example:
City of Philadelphia | Revenue Department links to http://undefinedphila.gov/revenue/realestatetax/

**Comment by laurenancona** [comment]
Thanks! Closed in https://github.com/CityOfPhiladelphia/analytics.phila.gov/commit/dbd0a35e238caedc76fba83f65efa23c25ddf23f

**Comment by michaelck** [comment]
:+1:
